name: Github CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cacher
      name: cacher
      with:
        path: |
          lua-all
          lua-all.tar.gz
          luajit-2.0
        key: ${{ runner.os }}-cacher-1
        restore-keys: |
          ${{ runner.os }}-cacher-1
    - name: Build & Test Linux
      run: ./.github/workflows/ci.linux.sh
      shell: bash
  build_mingw:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cacher
      name: cacher
      with:
        path: |
          lua-all
          lua-all.tar.gz
          luajit-2.0
        key: ${{ runner.os }}-cacher-1
        restore-keys: |
          ${{ runner.os }}-cacher-1
    - name: Build & Test Windows
      run: call .github\workflows\ci.mingw.bat
      shell: cmd

